services:
  it-tools:
    image: corentinth/it-tools:latest
    restart: unless-stopped
    environment:
      TZ: ${TZ:-UTC}
    networks:
      - it-tools
    ports:
      - "${IT_TOOLS_PORT:-25000}:80"


networks:
  it-tools: