services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    user: "${PUID:-1000}:${PGID:-1000}"
    # extends:
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    volumes:
      - ${IMMICH_UPLOAD_LOCATION:-../../volumes/storage/immich/library}:/data
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    networks:
      - immich
    ports:
      - '${IMMICH_PORT:-25001}:${IMMICH_PORT:-25001}'
    depends_on:
      - redis
      - database
    restart: always
    healthcheck:
      disable: false

  immich-machine-learning:
    # For hardware acceleration, add one of -[armnn, cuda, rocm, openvino, rknn] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://docs.immich.app/features/ml-hardware-acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, rocm, openvino, openvino-wsl, rknn] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - "${IMMICH_ML_CACHE_LOCATION:-../../volumes/storage/immich/ml-cache}:/cache"
    env_file:
      - .env
    networks:
      - immich
    restart: always
    healthcheck:
      disable: false

  redis:
    image: docker.io/valkey/valkey:8@sha256:81db6d39e1bba3b3ff32bd3a1b19a6d69690f94a3954ec131277b9a26b95b3aa
    # Note: Redis/Valkey manages its own user internally, no user override needed
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - immich
    restart: always

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    # Note: PostgreSQL manages its own user internally, no user override needed
    environment:
      POSTGRES_PASSWORD: ${IMMICH_DB_PASSWORD:-postgres}
      POSTGRES_USER: ${IMMICH_DB_USERNAME:-postgres}
      POSTGRES_DB: ${IMMICH_DB_DATABASE_NAME:-immich}
      POSTGRES_INITDB_ARGS: '--data-checksums'
      # DB_STORAGE_TYPE: 'HDD'
    networks:
      - immich
    volumes:
      - ${IMMICH_DB_DATA_LOCATION:-../../volumes/storage/immich/database}:/var/lib/postgresql/data
    shm_size: 128mb
    restart: always

networks:
  immich: